### PR TITLE
Drop IDE

### PR DESCRIPTION
**Pull request by tetsuo**
Hey Meinte, great work first of all 💯 

Wouldn't it be nice if IDE and evaluator were separate modules? This change drops IDE in favor of leaving _evan_, the evaluator by itself, along with some other improvements. What do you think?

### CODE REVIEW

**Comment by tetsuo** [comment]
Ping.

**Comment by dslmeinte** [comment]
Hi Onur,

(belated) Happy New Year!

I was under the impression you were going to explain the PR a bit: could you still do that?


Thanks,

Meinte

**Comment by tetsuo** [comment]
Heyy, Happy new year! 🎅 🎉 

Sorry, I was a bit busy this week and couldn't find time look into this again. Then I saw you've made a change and thought I have to ping you at some point :)

I am working on a new toy project (which I would like to share the details offline by the way) that uses the evalutor of evan only. Unfortunately, `evan` (as an evaluator only) is not listed on npm, and extracting the meta-model and keeping it up-to-date is not very optimal from consumer side, neither having to install React and mobx. UNIX simplicity gurus would be greatly happy if `evan` (the evaluator) was a separate npm module, preferably exporting its _latest_ metamodel- so consumers can also extend it, and etc.

So, this change proposes a new directory/project structure (along with some other minor improvements on how node.js APIs are being used and a minimal template engine for creating _the_ metamodel):

So, here we go:


```
.
├── docs
├── fixtures
│   ├── metamodel
│   │   ├── 0.1.0.json
│   │   └── 0.1.0.ts
│   └── programs
│       ├── external-objects.json
│       ├── fib.json
│       ├── out
│       │   ├── external-objects.json
│       │   ├── fib.json
│       │   ├── simple-func.json
│       │   └── simple.json
│       ├── simple-func.json
│       └── simple.json
├── latest.json -> fixtures/metamodel/0.1.0.json
├── package.json
├── readme.md
├── src
│   ├── bin
│   │   └── cmd.ts
│   ├── evan.ts
│   ├── index.ts
│   ├── issues.ts
│   ├── latest.ts -> ../fixtures/metamodel/0.1.0.ts
│   ├── metamodel.ts
│   └── test
│       ├── evan.ts
│       └── metamodel.ts
├── tsconfig.json
└── tslint.json
```

Going alphbetically.

* `docs`: Because `documentation` was too long 😏 

* `fixtures`: This folder contains all the metamodels and other _test fixtures_. The latest metamodel json file is linked to the `./latest.json` in root dir and typings file is to `src/latest.ts`. There are no prior build steps in anywhere to build those files, these are treated as source files, not artifacts. A library consumer should be able to do `require("xyz/latest.json")` to get the latest metamodel and metamodel typings (`index.ts` exports linked `./latest.ts`) as well. Likewise the results of evan programs here are generated manually using CLI.

* `latest.json`: This file is linked to the latest version of metamodel in `fixtures/metamodel` directory. This allows consumers to require the metamodel easily.

* `src/bin/cmd.ts`: CLI usage is as follows:

```
λ evan558/evan node lib/bin/cmd.js
evan FILE OPTIONS

Options:

  --semantics    Print TypeScript semantics.
  -v, --version  Show meta-model version.
  -h, --help     Show this message.

```

Passing `--semantics` arguments just outputs the latest metamodel to stdout:

```
 λ evan558/evan node lib/bin/cmd.js --semantics
export interface ISemanticsTyped {
  $sType: string
}
...
```

Or, you can evaluate programs directly:

```
λ evan558/evan node lib/bin/cmd.js fixtures/programs/fib.json
[ undefined, undefined, [ 1, 1, 2, 3, 5, 8, 13 ] ]
```

* `evan.ts`: This file contains only the evaluator with very minor changes.

* `index.ts`: Exports `evan` (the evaluator), `metamodel` (more on this below), `latest` (the metamodel), & `issues`. No IDE, no React, no Mobx, no heavy dependencies, just the core.

* `latest.ts`: This file is linked to latest typings in `fixtures/metamodel` folder.

* `metamodel.ts`: A minimal template engine for generating metamodel typings from json along with the base `MetaModel`.

The rest is pretty much same, except there is no IDE :)

**Comment by tetsuo** [comment]
So, a hypothetical IDE that depends on this module should be able to get the latest metamodel and evaluate on it easily:

```
import {ISemanticsTyped, evaluate} from "evan"
```

plus the semver ftw

**Comment by dslmeinte** [comment]
Ah, OK, now I'm starting to understand :)

I think splitting "`evan-core`" from the IDE is a great idea. However, at the moment, I'd rather keep everything as a mono-repo, to keep development simple until the IDE is really far enough to become it's own thing. I'm sure you're familiar with a particular situation where a multi-repo added a lot of unnecessary complexity ;) I really want to keep the bar for experimentation/evolution as low as possible, if only for myself.

Of course, this doesn't preclude from publishing the core, standalone evaluator as an NPM package. So, I want to propose the following:

1. Split this PR in a couple of smaller, focused ones. E.g. focus on: renaming and point 2.
2. Keep the IDE but split the IDE from the core evaluator, including the additions to that in this PR, and publishable to NPM.

**Comment by tetsuo** [comment]
Ok, I totally agree 😄 I'm closing this PR but I will come back again (not sure when though, so much hecticness these days)

By the way, have you seen this project? Amazing stuff: https://nodered.org

**Comment by dslmeinte** [comment]
I've seen Node-Red and it certainly brings that kind of development closer to the "citizen developer": good stuff :)

Good luck with the "hecticity"! :)

**Pull request closed without merging**
