### PR TITLE
Revert separate-ide PR

### PR DESCRIPTION
**Pull request by tetsuo**
Hey Meinte, I feel that this change has stalled the project :) and I also don't appreciate the change I made in here very much :)

I thought it is better to turn this into what it used to be, since I've already forked off.

Sorry for the mess 🚶

### CODE REVIEW

**Comment by dslmeinte** [comment]
Any stalling of the project could just as well have to do with me not having any time for it.

Are you really proposing to revert to my last commit and thereby destroying all your work?

**Comment by tetsuo** [comment]
Let me list the things that annoy me:

- Emojis in the commit messages
- All the lowercase letters
- Un-squashed commits
- `meta-model.ts` (building from templates) doesn't add much. What do you think?
- Broke the documentation a bit

Things that I like about that change:
- I like the nice CLI interface
- Tests are also fine
- Browser tests are also cool, but I have to say that I don't see any value with the `HTMLElement`, it sounds entirely out of context.

**Comment by dslmeinte** [comment]
So, can you save your work on the master branch to a different branch, then revert the master branch (as proposed), so we can cherry pick the things we like afterwards again (in a separate PR)?

**Comment by tetsuo** [comment]
I am on it, will get back to this sometime next week 👍  Closing the pr.

**Pull request closed without merging**
